### Summary table on climate stations
#### Iljin Victor, 13.10.2016
```{r master_location}

source("http://tmeits.github.io/24516/transect/setdw.R")
source("http://tmeits.github.io/24516/transect/clifiles.R") 

st.names <- c("Station_Code", "Station_Name", "Latitude", "Longitude", "Elevation", "Start_Y", 
    "End_Y", "FIT_Y")
#st.names.alt <- c("wmo_id", "city", "lat_prp", "lon_prp", "elev_baro", "start_year", "end_year", "fit_years", "path")
st.names.alt <- c("wmo_id", "city", "lat_prp", "lon_prp", "elev_baro", "start_year", "end_year", "path")
# http://meteocenter.net/_world_weather_stations.htm
st <- read.csv("master-location-identifier-database-20130801.csv", header = TRUE, sep = ",", 
    dec = ".")
#
getStationCode <- function(listFiles) {
    codes <- c(1:length(listFiles))
    for (i in 1:length(listFiles)) {
        listFiles.ss <- substr(listFiles[i], 1, 5)
        codes[i] <- as.numeric(listFiles.ss)
        cat(listFiles.ss, '\n')
    }
    return(codes)
}

#altai.code <- c(29998, 36229, 36231, 36246)
#altai.names <- c("ORLIK", "UST-KOKSA", "ONGUDAJ", "UST-ULAGAN")
#altai.code  <- getStationCode(altai.files)
# Work with weather data <http://aisori.meteo.ru/ClimateR> [R]
altai.aisori.files <- c("NA", "1", "NA", "NA")

#lena.code <- c("24051", "24261", "24643", "24652", "24668", "24768", "24859")
#lena.code <- getStationCode(lena.files)

#north.code <- getStationCode(north.files)

#yenisei.code <- getStationCode(yenisei.files)

#
getStationInfo <- function(stDF, stCode) {
    L <- length(stDF[, 1])
    for (i in 1:L) {
        if (!is.na(stDF[i, 12])) {
            # stDF$wmo_xref[i]
            if (stDF[i, "wmo_xref"] == stCode) 
                return(stDF[i, ])
        }
    }
}
# http://www.latlong.ru/
# http://www.sur-base.ru/?p=map
# http://meteoclub.ru/index.php?action=vthread&forum=16&topic=4021
#all.code <- c(altai.code, lena.code, north.code, yenisei.code)
all.code <- as.numeric(all.code)
all.code

ML <- matrix(c(1:(length(all.code) * 8)), nrow = length(all.code), ncol = 8, byrow = TRUE)
ml.df <- as.data.frame(ML)  #  converted to dataframe
ml.df <- setNames(ml.df, st.names)
ml.df <- setNames(ml.df, st.names.alt)  # assign names to the columns

for (i in 1:length(all.code)) {
    si <- getStationInfo(st, all.code[i])
    cat(si$wmo, as.character(si$city), round(si$lat_prp, 2), round(si$lon_prp, 2), si$elev_baro, 
        "\n")
    ml.df[i, 1] <- si$wmo
    ml.df[i, 2] <- as.character(si$city)
    ml.df[i, 3] <- round(si$lat_prp, 2)
    ml.df[i, 4] <- round(si$lon_prp, 2)
    ml.df[i, 5] <- si$elev_baro
    
    ml.df[i, 6] <- NA
    ml.df[i, 7] <- NA
    ml.df[i, 8] <- NA
    ml.df[i, 9] <- NA
    
    # missing values, fill from other sources
    if(all.code[i] == 24152){  # 
    ml.df[i, 5] <- 900
       ml.df[i, 2] <- "Verkhoyansk Range"
    }
    if(all.code[i] == 38401)  ml.df[i, 5] <- 25 # Ivan xlsx
    if(all.code[i] == 23077)  ml.df[i, 5] <- 197 # Norilsk http://www.weatherbase.com/weather/weather.php3?refer=&s=592273&cityname=Noril%27sk-Krasnoyarsk&refer=&cityname=Noril%27sk-Krasnoyarsk
}
str(ml.df)
ml.df.backup <- ml.df
```
#### Read the files at the stations and determination of years
```{r add-years}

addPeriod <- function(dfTransect, path, listFiles, cliPath) {
    for (i in 1:length(listFiles)) {
        cliSt <- read.csv(paste0(path, listFiles[i]), header = FALSE, sep = "", 
            dec = ".")
        cat("\nRead (", i, ")", listFiles[i], "\n")
        stCode <- as.numeric(substr(listFiles[i], 1, 5))
        beginY <- cliSt[1, 3]
        endY <- cliSt[length(cliSt[, 3]), 3]
        cat(stCode,beginY, endY,cliPath, "\n")
        dfTransect[dfTransect$wmo_id == stCode, ]$end_year <- endY
        dfTransect[dfTransect$wmo_id == stCode, ]$start_year <- beginY 
        dfTransect[dfTransect$wmo_id == stCode, ]$path <- as.character(cliPath)
    }
    return(dfTransect)
}

ml.df <- ml.df.backup
ml.df <- addPeriod(ml.df, paste0(mm_path, "/", alati.path,"/"), altai.files, alati.path)
ml.df <- addPeriod(ml.df, paste0(mm_path, "/cli/lena/"), lena.files, lena.path)
ml.df <- addPeriod(ml.df, paste0(mm_path, "/cli/north/"), north.files, north.path)
ml.df <- addPeriod(ml.df, paste0(mm_path, "/cli/yenisei/"), yenisei.files, yenisei.path)
ml.df <- addPeriod(ml.df, paste0(mm_path, "/cli/aisori/"), aisori.files, aisori.path)
head(ml.df) 
print("Read done...")
```
#### writeXLSX
```{r writeXLSX}
Sys.setenv(R_ZIPCMD = paste0(mm_path, "/bin/zip.exe"))  ## path to zip.exe
require(openxlsx)
openxlsx::write.xlsx(ml.df, file = "master_location.xlsx")


print("Write done...")
```
To refer to the array: 

Bulygina O. N., Veselov V. M., Alexandrova, T. M., Korshunova N. N. "DESCRIPTION OF ARRAY DATA ON ATMOSPHERIC PHENOMENA AT THE METEOROLOGICAL STATIONS OF RUSSIA."
The certificate of state registration database No. 2015620081
<http://meteo.ru/data/345-atmosfernye-yavleniya-sroki>

```{r}
# runAllChunks("master_location.Rmd")
# Rmd2R("master_location.Rmd", "master_location.R")
# source("master_location.R")
print("End.")
```



















